#!/usr/bin/env bash
# Create/update a local .env with session secret and password hash.
# Detect user-domain install paths and write .install-paths for the Makefile.
# Usage: ./scripts/configure.sh [--paths-only] [path-to-.env]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PATHS_FILE="$ROOT/.install-paths"
EXAMPLE="$ROOT/.env.example"
PATHS_ONLY=0
ENV_FILE=""

usage() {
	cat >&2 <<'EOF'
Usage: ./scripts/configure.sh [--paths-only] [path-to-.env]

  --paths-only   Write .install-paths only (no .env / password prompt)
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--paths-only)
		PATHS_ONLY=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	-*)
		echo "unknown option: $1" >&2
		usage
		exit 2
		;;
	*)
		if [[ -n "$ENV_FILE" ]]; then
			echo "unexpected argument: $1" >&2
			usage
			exit 2
		fi
		ENV_FILE="$1"
		shift
		;;
	esac
done

ENV_FILE="${ENV_FILE:-$ROOT/.env}"

path_on_path() {
	local dir="$1"
	case ":$PATH:" in
	*":$dir:"*) return 0 ;;
	*) return 1 ;;
	esac
}

# Prefer a candidate if it already exists or is already on PATH.
pick_existing_or_on_path() {
	local d
	for d in "$@"; do
		if [[ -d "$d" ]] || path_on_path "$d"; then
			printf '%s\n' "$d"
			return 0
		fi
	done
	return 1
}

same_dir() {
	local a b
	a="$(realpath -m "$1")"
	b="$(realpath -m "$2")"
	[[ "$a" == "$b" ]]
}

detect_paths() {
	if ! command -v go >/dev/null 2>&1; then
		echo "go not found" >&2
		exit 1
	fi

	if [[ -z "${HOME:-}" ]]; then
		echo "HOME is not set" >&2
		exit 1
	fi

	if [[ -n "${GOBIN:-}" ]]; then
		JOBAPP_GOBIN="$GOBIN"
	else
		JOBAPP_GOBIN="$(go env GOBIN)"
		if [[ -z "$JOBAPP_GOBIN" ]]; then
			local gopath
			gopath="$(go env GOPATH)"
			JOBAPP_GOBIN="${gopath%%:*}/bin"
		fi
	fi

	if [[ -n "${XDG_BIN_HOME:-}" ]]; then
		JOBAPP_USERBIN="$XDG_BIN_HOME"
	elif JOBAPP_USERBIN="$(pick_existing_or_on_path "$HOME/.local/bin" "$HOME/bin")"; then
		:
	else
		JOBAPP_USERBIN="$HOME/.local/bin"
	fi

	JOBAPP_DATADIR="${XDG_DATA_HOME:-$HOME/.local/share}/jobapp"
	JOBAPP_CONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/jobapp"
	JOBAPP_UNITDIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
	JOBAPP_ENV="$JOBAPP_CONFIGDIR/.env"
	JOBAPP_DB="$JOBAPP_DATADIR/jobs.db"

	if same_dir "$JOBAPP_GOBIN" "$JOBAPP_USERBIN"; then
		JOBAPP_BIN="$JOBAPP_GOBIN/jobapp"
		JOBAPP_SYMLINK=0
	else
		JOBAPP_BIN="$JOBAPP_USERBIN/jobapp"
		JOBAPP_SYMLINK=1
	fi
}

write_install_paths() {
	local tmp
	tmp="$(mktemp)"
	cat >"$tmp" <<EOF
# Generated by scripts/configure.sh — do not commit
JOBAPP_GOBIN := ${JOBAPP_GOBIN}
JOBAPP_USERBIN := ${JOBAPP_USERBIN}
JOBAPP_BIN := ${JOBAPP_BIN}
JOBAPP_SYMLINK := ${JOBAPP_SYMLINK}
JOBAPP_DATADIR := ${JOBAPP_DATADIR}
JOBAPP_CONFIGDIR := ${JOBAPP_CONFIGDIR}
JOBAPP_ENV := ${JOBAPP_ENV}
JOBAPP_UNITDIR := ${JOBAPP_UNITDIR}
JOBAPP_DB := ${JOBAPP_DB}
EOF
	mv "$tmp" "$PATHS_FILE"
}

print_paths() {
	echo "install paths:"
	echo "  Go bin:     $JOBAPP_GOBIN"
	echo "  user bin:   $JOBAPP_USERBIN"
	echo "  ExecStart:  $JOBAPP_BIN"
	echo "  data:       $JOBAPP_DATADIR"
	echo "  config:     $JOBAPP_CONFIGDIR"
	echo "  units:      $JOBAPP_UNITDIR"
	if [[ "$JOBAPP_SYMLINK" == "1" ]]; then
		echo "  symlink:    $JOBAPP_USERBIN/jobapp -> $JOBAPP_GOBIN/jobapp"
	else
		echo "  symlink:    skipped (Go bin and user bin are the same directory)"
	fi
}

set_kv() {
	local key="$1" val="$2" tmp
	tmp="$(mktemp)"
	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "$line" == "$key="* ]]; then
			printf '%s=%s\n' "$key" "$val"
		else
			printf '%s\n' "$line"
		fi
	done <"$ENV_FILE" >"$tmp"
	mv "$tmp" "$ENV_FILE"
}

detect_paths
write_install_paths
echo "wrote $PATHS_FILE"
print_paths

if [[ "$PATHS_ONLY" -eq 1 ]]; then
	exit 0
fi

if [[ ! -f "$EXAMPLE" ]]; then
	echo "missing $EXAMPLE" >&2
	exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
	read -r -p "$ENV_FILE already exists. Overwrite from .env.example? [y/N] " ans
	case "$ans" in
	[yY] | [yY][eE][sS]) ;;
	*)
		echo "aborted"
		exit 1
		;;
	esac
fi

cp "$EXAMPLE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE"

if ! command -v openssl >/dev/null 2>&1; then
	echo "openssl not found" >&2
	exit 1
fi

secret="$(openssl rand -hex 32)"
set_kv JOBAPP_SESSION_SECRET "$secret"
echo "set JOBAPP_SESSION_SECRET"

set_kv JOBAPP_DB "$JOBAPP_DB"
echo "set JOBAPP_DB=$JOBAPP_DB"

read -r -s -p "Site password: " password
echo
if [[ -z "$password" ]]; then
	echo "password required" >&2
	exit 1
fi
read -r -s -p "Confirm password: " password2
echo
if [[ "$password" != "$password2" ]]; then
	echo "passwords do not match" >&2
	exit 1
fi

hash="$(go run "$ROOT/scripts/hashpassword" "$password")"
set_kv JOBAPP_PASSWORD_HASH "$hash"
echo "set JOBAPP_PASSWORD_HASH"

echo "done — fill remaining secrets in $ENV_FILE (OpenRouter, Telegram, etc.)"
